# Generated by Django 5.1.1 on 2024-10-07 06:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0002_review_stars'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovieReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stars', models.IntegerField(choices=[(1, '⭐'), (2, '⭐ ⭐'), (3, '⭐ ⭐ ⭐'), (4, '⭐ ⭐ ⭐ ⭐'), (5, '⭐ ⭐ ⭐ ⭐ ⭐')], default=5)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie_app.movie')),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie_app.review')),
            ],
        ),
    ]
